#:schema node_modules/wrangler/config-schema.json
name = "redirector"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[kv_namespaces]]
binding = "RULES"
id = "db155307ae624ff5a65e34d7b900a3d1"
